# Generated by Django 4.0.5 on 2022-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('ip', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
